[package]
name = "golden_token"
version = "0.1.0"

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.9.0" }
starknet = "2.4.0"
arcade_account = { git = "https://github.com/BibliothecaDAO/arcade-account", branch = "next" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
allowed-libfuncs = true
